### ISSUE TITLE
Allow enumerables to return non-const references

### ISSUE THREAD

**Issue by garyng** [coveo/linq#1]
Is that possible for the linq operations to return a vector of references to the element in the original vectors? like a vector of reference_wrapper?
It's useful when the object is stored as value(vector<T>) but I want the reference to the original element in the vector after some linq operations.

Is that possible? Or there is some alternative ways?

Thanks 😄

**Comment by clechasseur** [comment]
Some operators, like `distinct`, `except`, etc. already work this way - they return references to the elements in the original sequences. Other operators cannot because they transform the elements, like `select`.

Were you having problems with a specific operator that I could look at?

**Comment by garyng** [comment]
Uhmm, let say I want to modify the content of all element from a subset of original elements...
```
vector<Request> requests = <source of things here>
	| where([&](Request request) { return <some predicate>; })
	| to_vector();
for (auto request : requests)
{
	request.Status = "modify something here...";
}
```
The changes will not be reflected back to the original source.
(Am I giving the return type right?)

PS: I'm very very new to C++, using this for a school project. 😄

**Comment by clechasseur** [comment]
`to_vector` cannot return references, because if they come from a temporary, that would result in invalid refs. However, it's not necessary to actually convert this to a `vector` - you can use the result of the `where` operator directly:
```
auto requests = <source of things here>
              | where([&](const Request& request) { return <some predicate>; });
for (auto& request : requests) {
    request.Status = "modify something here...";
}
```
This way, you should be able to modify the elements of the original sequence directly.

**Comment by garyng** [comment]
Thanks! I will give it a try!

**Comment by clechasseur** [comment]
I tried it and it doesn't work. I forgot that the LINQ operators generally return `enumerable`s, which always return const refs.

This was a design choice to keep `enumerable` simple (otherwise you'd have to deal with `const`-ness in a lot of places)... so I'd say that, right now, it's a limitation of the library and it's not possible to do what you're trying to do. Sorry.

**Comment by garyng** [comment]
Uhmmm.. Never mind! 
There is always an alternative, right? 
😄

**Comment by clechasseur** [comment]
I'll turn this into an enhancement - there might be a clean way of doing it. :-)

**Comment by clechasseur** [comment]
There is [a new pre-release version](https://github.com/coveo/linq/releases/tag/v2.0-alpha) of `coveo::linq` that now supports non-const references. This means the following code should work:

```
std::vector<int> v = { 42, 23, 66, 7 };
using namespace coveo::linq;
auto evens = from(v)
           | where([](int i) { return i % 2 == 0; });
for (int& i : evens) {
    i *= 2;
}
// v is now { 84, 23, 132, 7 }
```

Feel free to try it and see how it goes on your end. I'm going to perform a few more tests before I release it officially.

**Comment by garyng** [comment]
Ok sure!
Thanks! 😄

**Comment by clechasseur** [comment]
This is now live as of release 2.0.

**Comment by garyng** [comment]
Seems like after https://github.com/coveo/linq/commit/28f22828d2bd196da0ca3ca9982b9cca1b8a6c1c, operators like `last`, `first`, etc do not return reference to the element anymore? Anyway to get back the original behavior?

_after almost 1 year, I came back and used this library for my uni project again... and man C++ still feels like dark magic to me..._

**Comment by clechasseur** [comment]
Yeah, that's actually a bugfix for them to work with some LINQ operators... I don't really like the current implementation of `enumerable` that returns references to temporaries inside the iterator, it breaks the C++ way of doing things. It's the best we have right now, but it's definitely on my radar to be modified in some way in the future.
